<?php
$z[0]=Array("field","",42,70);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",72,101);
$z[1][4]['name']="typename";
$z[2]=Array("field","",142,170);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n\r\n<li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n\r\n",233,418);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>