<?php
$z[0]=Array("global","",103,128);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",194,219);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",281,306);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",339,365);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",493,520);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",593,620);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",623,649);
$z[6][4]['name']="cfg_webname";

?>